# Generated by Django 5.1.4 on 2025-04-10 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedListing',
            new_name='SavedProduct',
        ),
        migrations.RenameField(
            model_name='adboost',
            old_name='listing',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='listing',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='listing',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='savedproduct',
            old_name='listing',
            new_name='product',
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='savedproduct',
            unique_together={('user', 'product')},
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('comm_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOOST', 'Boost Message')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by_admin', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
